# Stubs for google.cloud.client (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

class _ClientFactoryMixin:
    @classmethod
    def from_service_account_json(cls, json_credentials_path, *args, **kwargs): ...

class Client(_ClientFactoryMixin):
    SCOPE: Any = ...
    def __init__(self, credentials: Optional[Any] = ..., _http: Optional[Any] = ...) -> None: ...

class _ClientProjectMixin:
    project: Any = ...
    def __init__(self, project: Optional[Any] = ...) -> None: ...

class ClientWithProject(Client, _ClientProjectMixin):
    def __init__(self, project: Optional[Any] = ..., credentials: Optional[Any] = ..., _http: Optional[Any] = ...) -> None: ...
