# Stubs for google.cloud.pubsub_v1.subscriber (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from google.cloud.pubsub_v1.subscriber.client import Client as Client
