# Stubs for google.cloud.bigtable (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from google.cloud.bigtable.client import Client as Client

# Names in __all__ with no definition:
#   __version__
