# Stubs for google.cloud.pubsub_v1 (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from google.cloud.pubsub_v1 import publisher, subscriber, types as types
from typing import Any

class PublisherClient(publisher.Client):
    __doc__: Any = ...

class SubscriberClient(subscriber.Client):
    __doc__: Any = ...
