# Stubs for google (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

cloud = ... # type: Any
iam = ... # type: Any
logging = ... # type: Any
