# Stubs for google.auth._default (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def default(scopes: Optional[Any] = ..., request: Optional[Any] = ...): ...
