# Stubs for google.cloud.bigquery (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from google.cloud.bigquery._helpers import DEFAULT_RETRY as DEFAULT_RETRY
from google.cloud.bigquery.client import Client as Client
from google.cloud.bigquery.dataset import AccessEntry as AccessEntry, Dataset as Dataset, DatasetReference as DatasetReference
from google.cloud.bigquery.external_config import BigtableColumn as BigtableColumn, BigtableColumnFamily as BigtableColumnFamily, BigtableOptions as BigtableOptions, CSVOptions as CSVOptions, ExternalConfig as ExternalConfig, GoogleSheetsOptions as GoogleSheetsOptions
from google.cloud.bigquery.job import CopyJob as CopyJob, CopyJobConfig as CopyJobConfig, ExtractJob as ExtractJob, ExtractJobConfig as ExtractJobConfig, LoadJob as LoadJob, LoadJobConfig as LoadJobConfig, QueryJob as QueryJob, QueryJobConfig as QueryJobConfig
from google.cloud.bigquery.query import ArrayQueryParameter as ArrayQueryParameter, ScalarQueryParameter as ScalarQueryParameter, StructQueryParameter as StructQueryParameter, UDFResource as UDFResource
from google.cloud.bigquery.schema import SchemaField as SchemaField
from google.cloud.bigquery.table import Table as Table, TableReference as TableReference

# Names in __all__ with no definition:
#   __version__
