# Stubs for google.cloud.pubsub_v1.publisher (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from google.cloud.pubsub_v1.publisher.client import Client as Client
