# Stubs for google.cloud.storage (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from google.cloud.storage.batch import Batch as Batch
from google.cloud.storage.blob import Blob as Blob
from google.cloud.storage.bucket import Bucket as Bucket
from google.cloud.storage.client import Client as Client

# Names in __all__ with no definition:
#   __version__
