# Stubs for google.cloud.storage._http (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from google.cloud import _http
from typing import Any

class Connection(_http.JSONConnection):
    API_BASE_URL: Any = ...
    API_VERSION: str = ...
    API_URL_TEMPLATE: str = ...
